import express from "express";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";

const router = express.Router();

router.get("/pdf", (req, res) => {
  const title = req.query.title ? String(req.query.title) : "Light Vision Report";
  const doc = new PDFDocument({ size: "A4", margin: 48 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${title.replace(/[^a-zA-Z0-9_-]/g, "_")}.pdf"`);

  doc.pipe(res);
  doc.fontSize(24).fillColor("#0f172a").text(title, { align: "left" });
  doc.moveDown();
  doc.fontSize(12).fillColor("#475569").text("This document was generated by the Light Vision backend utility route.");
  doc.moveDown();
  doc.text("Thank you for using the Light Vision property toolkit.");

  doc.end();
});

router.get("/qrcode", async (req, res) => {
  const text = String(req.query.text ?? "Light Vision Property");
  try {
    const buffer = await QRCode.toBuffer(text, { type: "png", width: 300 });
    res.setHeader("Content-Type", "image/png");
    res.send(buffer);
  } catch (error) {
    res.status(500).json({ error: "Failed to generate QR code." });
  }
});

export default router;
